apiVersion: apps/v1
kind: Deployment
metadata:
  name: shuffle-kstreams
spec:
  selector:
    matchLabels:
      app: shuffle-kstreams
  replicas: 9
  template:
    metadata:
      labels:
        app: shuffle-kstreams
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: shuffle-kstreams
          image: ghcr.io/dynatrace-research/shufflebench/shuffle-kstreams:latest
          ports:
            - containerPort: 5555
              name: jmx
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: "theodolite-kafka-kafka-bootstrap:9092"
            - name: MATCHER_ZIPF_NUM_RULES
              value: "1000000"
            - name: MATCHER_ZIPF_TOTAL_SELECTIVITY
              value: "0.2"
            - name: MATCHER_ZIPF_S
              value: "0.0"
            - name: CONSUMER_INIT_COUNT_RANDOM
              value: "true"
            - name: "KAFKASTREAMS__COMMIT_INTERVAL_MS__"
              value: "5000"
            # - name: "KAFKASTREAMS__MAX_POLL_RECORDS__"
            #   value: "500"
            # - name: "KAFKASTREAMS__LINGER_MS__"
            #   value: "0"
            # - name: "KAFKASTREAMS__NUM_STREAM_THREADS__"
            #   value: "4"
            - name: JAVA_TOOL_OPTIONS
              value: "-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=5555"
          resources:
            limits:
              memory: 4Gi
              cpu: 1000m
        - name: prometheus-jmx-exporter
          image: "solsson/kafka-prometheus-jmx-exporter@sha256:6f82e2b0464f50da8104acd7363fb9b995001ddff77d248379f8788e78946143"
          command:
            - java
            - -XX:+UnlockExperimentalVMOptions
            - -XX:+UseCGroupMemoryLimitForHeap
            - -XX:MaxRAMFraction=1
            - -XshowSettings:vm
            - -jar
            - jmx_prometheus_httpserver.jar
            - "5556"
            - /etc/jmx-aggregation/jmx-kafka-prometheus.yml
          ports:
            - containerPort: 5556
          volumeMounts:
            - name: jmx-config
              mountPath: /etc/jmx-aggregation
      volumes:
        - name: jmx-config
          configMap:
            name: shuffle-kstreams-jmx-configmap
